// Code generated by go-swagger; DO NOT EDIT.

package get

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSudokuHandlerFunc turns a function with the right signature into a get sudoku handler
type GetSudokuHandlerFunc func(GetSudokuParams) GetSudokuResponder

// Handle executing the request and returning a response
func (fn GetSudokuHandlerFunc) Handle(params GetSudokuParams) GetSudokuResponder {
	return fn(params)
}

// GetSudokuHandler interface for that can handle valid get sudoku params
type GetSudokuHandler interface {
	Handle(GetSudokuParams) GetSudokuResponder
}

// NewGetSudoku creates a new http.Handler for the get sudoku operation
func NewGetSudoku(ctx *middleware.Context, handler GetSudokuHandler) *GetSudoku {
	return &GetSudoku{Context: ctx, Handler: handler}
}

/* GetSudoku swagger:route GET /get get getSudoku

GetSudoku get sudoku API

*/
type GetSudoku struct {
	Context *middleware.Context
	Handler GetSudokuHandler
}

func (o *GetSudoku) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSudokuParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
