// Code generated by go-swagger; DO NOT EDIT.

package get

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"silly-sudoku/internal/oapi/models"
)

// GetSudokuOKCode is the HTTP code returned for type GetSudokuOK
const GetSudokuOKCode int = 200

/*GetSudokuOK sudoku to be solved

swagger:response getSudokuOK
*/
type GetSudokuOK struct {

	/*
	  In: Body
	*/
	Payload *models.Sudoku `json:"body,omitempty"`
}

// NewGetSudokuOK creates GetSudokuOK with default headers values
func NewGetSudokuOK() *GetSudokuOK {

	return &GetSudokuOK{}
}

// WithPayload adds the payload to the get sudoku o k response
func (o *GetSudokuOK) WithPayload(payload *models.Sudoku) *GetSudokuOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sudoku o k response
func (o *GetSudokuOK) SetPayload(payload *models.Sudoku) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSudokuOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetSudokuOK) GetSudokuResponder() {}

/*GetSudokuDefault generic error response

swagger:response getSudokuDefault
*/
type GetSudokuDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetSudokuDefault creates GetSudokuDefault with default headers values
func NewGetSudokuDefault(code int) *GetSudokuDefault {
	if code <= 0 {
		code = 500
	}

	return &GetSudokuDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get sudoku default response
func (o *GetSudokuDefault) WithStatusCode(code int) *GetSudokuDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get sudoku default response
func (o *GetSudokuDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get sudoku default response
func (o *GetSudokuDefault) WithPayload(payload *models.Error) *GetSudokuDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sudoku default response
func (o *GetSudokuDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSudokuDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetSudokuDefault) GetSudokuResponder() {}

type GetSudokuNotImplementedResponder struct {
	middleware.Responder
}

func (*GetSudokuNotImplementedResponder) GetSudokuResponder() {}

func GetSudokuNotImplemented() GetSudokuResponder {
	return &GetSudokuNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.GetSudoku has not yet been implemented",
		),
	}
}

type GetSudokuResponder interface {
	middleware.Responder
	GetSudokuResponder()
}
