# Options for analysis running.
run:
  # See the dedicated "run" documentation section.
  option: value
# output configuration options
output:
  # See the dedicated "output" documentation section.
  option: value
# All available settings of specific linters.
linters-settings:
  # See the dedicated "linters-settings" documentation section.
  option: value
linters:
  # See the dedicated "linters" documentation section.
  option: value
  enable-all: true
  disable:
    - exhaustivestruct # The owner seems to have abandoned the linter.  Replaced by exhaustruct.
    - scopelint # The repository of the linter has been deprecated by the owner.  Replaced by exportloopref
    - golint # The repository of the linter has been archived by the owner.  Replaced by revive.
    - maligned # The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment
    - interfacer # The repository of the linter has been archived by the owner.
    - varnamelen # useless in the scope of this project
    - gofumpt # useless in the scope of this project
    - gci # useless in the scope of this project
issues:
  # See the dedicated "issues" documentation section.
  option: value
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:    # Exclude `lll` issues for long lines with `go:generate`.
    - path: internal/oapi/
      linters:
        - lll
severity:
  # See the dedicated "severity" documentation section.
  option: value
