// Code generated by go-swagger; DO NOT EDIT.

package check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CheckSudokuHandlerFunc turns a function with the right signature into a check sudoku handler
type CheckSudokuHandlerFunc func(CheckSudokuParams) CheckSudokuResponder

// Handle executing the request and returning a response
func (fn CheckSudokuHandlerFunc) Handle(params CheckSudokuParams) CheckSudokuResponder {
	return fn(params)
}

// CheckSudokuHandler interface for that can handle valid check sudoku params
type CheckSudokuHandler interface {
	Handle(CheckSudokuParams) CheckSudokuResponder
}

// NewCheckSudoku creates a new http.Handler for the check sudoku operation
func NewCheckSudoku(ctx *middleware.Context, handler CheckSudokuHandler) *CheckSudoku {
	return &CheckSudoku{Context: ctx, Handler: handler}
}

/* CheckSudoku swagger:route POST /check check checkSudoku

CheckSudoku check sudoku API

*/
type CheckSudoku struct {
	Context *middleware.Context
	Handler CheckSudokuHandler
}

func (o *CheckSudoku) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCheckSudokuParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
