// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Original encrypted sudoku original returned by the `/get` and to be used later with `/check`
//
// swagger:model original
type Original string

// Validate validates this original
func (m Original) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this original based on context it is used
func (m Original) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
