// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Row row
//
// swagger:model row
type Row []int32

// Validate validates this row
func (m Row) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this row based on context it is used
func (m Row) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
