// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Sudoku server
//
//  # Sudoku generation and verification server
//  ## List of all custom errors
//  First number is HTTP Status code, second is value of "code" field in returned JSON object, text description may or may not match "message" field in returned JSON object.
//  - 400.700: Provided solution does not match to the original sudoku.
//  - 400.701: Original field could not be decrypted
//  - 422.702: Solution is invalid
//
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /
//  Version: 4.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
